server:
  port: 8080
spring:
  application.name: universidad-merce
  datasource:
    url: jdbc:mariadb://localhost:3306/universidad
    username: root
    password: root
  jpa.hibernate.ddl-auto: create
api.url: https://swapi.co/api/
